global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using eAgendaMedica.Dominio.ModuloCirurgia;
global using eAgendaMedica.Dominio.ModuloConsulta;
global using eAgendaMedica.Dominio.ModuloMedico;
global using eAgendaMedica.Dominio.ModuloPaciente;
global using eAgendaMedica.Dominio.Compartilhado;
global using FluentAssertions;
global using FluentValidation.Results;
global using FizzWare.NBuilder;